### ISSUE TITLE
TOML parse error when starting yazi

### ISSUE THREAD

**Issue by ruiiiijiiiiang** [mgumz/yazi-plugin-bat#1]
Hi, first time using yazi plugins so I'm not sure if I'm doing everything correctly. But I set up the configs as instructed by the README and now yazi is reporting a parse error.

![Screenshot 2024-10-18 at 11 00 46](https://github.com/user-attachments/assets/bbad2b39-c53d-4ac7-8cd8-296e31a9867a)

Anything I can do to fix this?

**Comment by mgumz** [comment]
@ruiiiijiiiiang its most likely an inconsistency between the plugin when i created it and the interface yazi provides right now.

**Comment by ruiiiijiiiiang** [comment]
@mgumz I figured it out. In the yazi.toml config file, I need to use `run` instead of `exec`. Everything works perfectly. Thank you.
